# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title: Daniel Lázaro
email: dlazaro.libros@gmail.com
description: Los libros de Daniel Lázaro
url: "https://dlazaroi.github.io"
domain: "dlazaroi.github.io"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
    
locale: es-ES

author:
  name: "Daniel Lázaro Iglesias"
  avatar: "/assets/images/avatar-icon.avif"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/dlazaroi"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/dlazaro.libros"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/dlazaroi"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/dlazaro.libros"
atom_feed:
  hide: true

logo: "/assets/img/avatar-icon.avif"

head_scripts:
  - /assets/scripts/newsletter.js


collections:
  books:
    sort_by: order
    output: true
  sections:

minimal_mistakes_skin: "dark" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

analytics:
  provider: google-gtag
  google:
    tracking_id: G-GKMQ1F2DYM

